[project]
name = "phonietv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Francis Conroy", email = "francisc@posteo.net" }
]
requires-python = ">=3.13"
dependencies = [
    "adafruit-circuitpython-pn532>=2.4.9",
    "blinkt>=0.1.2 ; sys_platform == 'linux'",
    "python-vlc>=3.0.21203",
]

[project.scripts]
phonietv = "phonietv.__main__:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "time-machine>=3.3.1",
]
